apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad00g-frontend-deployment
  namespace: ad00g
  labels:
    app: ad00g-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ad00g-frontend
  template:
    metadata:
      labels:
        app: ad00g-frontend
    spec:
      containers:
        - name: web
          image: robersonandrade/ad00g-frontend:1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
