apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: todo-app
  labels:
    app: todo-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: todo-server
  sessionAffinity: None
