apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: todo-app
type: Opaque
data:
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u # "your-super-secret-jwt-key-change-this-in-production" in base64
  JWT_EXPIRES_IN: MjRo # "24h" in base64
