apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad00g-backend-deployment
  namespace: ad00g
  labels:
    app: ad00g-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ad00g-backend
  template:
    metadata:
      labels:
        app: ad00g-backend
    spec:
      containers:
        - name: backend
          image: andrewutfpr/backend-ad00g:1.3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ad00g-backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ad00g-backend-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
