apiVersion: v1
kind: Service
metadata:
  name: ad00g-backend-service
  namespace: ad00g
  labels:
    app: ad00g-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ad00g-backend
  sessionAffinity: None
