apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: todo-app
  labels:
    app: todo-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: todo-web
  sessionAffinity: None
